# Generated by Django 3.1.1 on 2020-09-12 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200912_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 6, 55, 63093), verbose_name='date published'),
        ),
    ]
