# Generated by Django 3.1.1 on 2020-09-11 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200911_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 12, 21, 0, 709247), verbose_name='date published'),
        ),
    ]
